# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'products/images/'),
        ),
    ]
