# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160423_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Cart'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name_first',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name_last',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='street_1',
            field=models.CharField(max_length=50, verbose_name=b'Address 1'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='street_2',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'Address 2'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=b'products/images/'),
        ),
    ]
