# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 06:37
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160423_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
