# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(default='a@b.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='province',
            field=models.CharField(default='BC', max_length=30),
            preserve_default=False,
        ),
    ]
