# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20160531_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
