# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160531_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.TextField(),
        ),
    ]
